# Project specific variables
DOCKER_PATH := ./docker
PROJECT_PATH := ./src

# Retrieve the Makefile used to manage the Docker environment
export COMPOSE_FILE	:= $(DOCKER_PATH)/docker-compose.yml
include $(DOCKER_PATH)/Makefile
